### ISSUE TITLE
base app is broken

### ISSUE THREAD

**Issue by gad2103** [javamonn/todo-angular-flux#6]
`gulp serve` --> localhost:8080  just shows a blank page...

node version = 0.12

**Comment by javamonn** [comment]
Hi, thanks for opening an issue.

It looks like the most recent [0.2.12 Reflux release](https://github.com/reflux/refluxjs/releases/tag/v0.2.12) yesterday removed the compiled `dist/reflux.js` from the package that I was using. I updated the package.json to pin Reflux at 0.2.11 for now and everything appears to be working for me again.

Please report back if everything looks good on your end as well.

**Comment by gad2103** [comment]
will do. thanks!

**Comment by javamonn** [comment]
Closed per https://github.com/javamonn/Angular-TodoMVC-Redux/commit/67c8ea8362cf238cc601abec44bfdd289630b781.
